blank_issues_enabled: false
contact_links:
  - name: Need help?
    url: https://github.com/mozilla/pdf.js/discussions
    about: If you need help on how to use PDF.js, please open a discussion where other community members can reply
