name: Sync Fork

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: StileEducation
          base: master
          head: master
          pr_title: "Upstream Change via Fork Sync"
